### ISSUE TITLE
Migrate to use aegir

### ISSUE THREAD

**Issue by nginnever** [libp2p/js-libp2p-distributed-record-store#2]
Regarding <a href="https://github.com/dignifiedquire/dignified.js/issues/1">updates</a>

This module's tests depend on these <a href="https://github.com/nginnever/interface-record-store/blob/dignified/tests/base-test.js">tests</a> in tape. 

Should we leave these alone or try a mocha conversion or use a dignified hack to run tape tests in mocha?

cc @dignifiedquire @diasdavid

**Comment by diasdavid** [comment]
We will update them to use mocha too. Wanna hack that @nginnever ?
